---
- name: Update web servers
  hosts: all
  #remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: Ensure that apache is started
    ansible.builtin.service:
      name: httpd
      state: started
